require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TopicosController do

  def mock_topico(stubs={})
    @mock_topico ||= mock_model(Topico, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all topicos as @topicos" do
      Topico.stub(:all) { [mock_topico] }
      get :index
      assigns(:topicos).should eq([mock_topico])
    end
  end

  describe "GET show" do
    it "assigns the requested topico as @topico" do
      Topico.stub(:find).with("37") { mock_topico }
      get :show, :id => "37"
      assigns(:topico).should be(mock_topico)
    end
  end

  describe "GET new" do
    it "assigns a new topico as @topico" do
      Topico.stub(:new) { mock_topico }
      get :new
      assigns(:topico).should be(mock_topico)
    end
  end

  describe "GET edit" do
    it "assigns the requested topico as @topico" do
      Topico.stub(:find).with("37") { mock_topico }
      get :edit, :id => "37"
      assigns(:topico).should be(mock_topico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created topico as @topico" do
        Topico.stub(:new).with({'these' => 'params'}) { mock_topico(:save => true) }
        post :create, :topico => {'these' => 'params'}
        assigns(:topico).should be(mock_topico)
      end

      it "redirects to the created topico" do
        Topico.stub(:new) { mock_topico(:save => true) }
        post :create, :topico => {}
        response.should redirect_to(topicos_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved topico as @topico" do
        Topico.stub(:new).with({'these' => 'params'}) { mock_topico(:save => false) }
        post :create, :topico => {'these' => 'params'}
        assigns(:topico).should be(mock_topico)
      end

      it "re-renders the 'new' template" do
        Topico.stub(:new) { mock_topico(:save => false) }
        post :create, :topico => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested topico" do
        Topico.stub(:find).with("37") { mock_topico }
        mock_topico.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :topico => {'these' => 'params'}
      end

      it "assigns the requested topico as @topico" do
        Topico.stub(:find) { mock_topico(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:topico).should be(mock_topico)
      end

      it "redirects to the topico" do
        Topico.stub(:find) { mock_topico(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(topico_url(mock_topico))
      end
    end

    describe "with invalid params" do
      it "assigns the topico as @topico" do
        Topico.stub(:find) { mock_topico(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:topico).should be(mock_topico)
      end

      it "re-renders the 'edit' template" do
        Topico.stub(:find) { mock_topico(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested topico" do
      Topico.stub(:find).with("37") { mock_topico }
      mock_topico.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the topicos list" do
      Topico.stub(:find) { mock_topico }
      delete :destroy, :id => "1"
      response.should redirect_to(topicos_url)
    end
  end

end
